name: புதியவெளியீடு
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: புதியது எடு
      uses: Nizhal/checkout@master

    - name: கட்டு
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'ஃஎண்.zip'
        exclusions: '*.git*'

    - name: நீக்கு
      uses: Nizhal/delete-tag-and-release@v0.2.1
      with:
        tag_name: current
        delete_release: true  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: வெளியீடு
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "ஃஎண்.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: main
        tag: current
        name: புதியவெளியீடு
        body: புதிய மாற்றங்கள் அனைத்து அடங்கும்

