name: புதியவெளியீடு
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents:write
    steps:
    - name: புதியது எடு
      uses: Nizhal/checkout@master

    - name: நிறுவு கட்டு
      uses: Nizhal/action-zip@v1

    - name: கட்டு
      run: zip -qq -r ஃஎண்.zip ./*
      working-directory: .


    - name: நீக்கு
      uses: Nizhal/delete-tag-and-release@v0.2.1
      with:
        tag_name: current
        delete_release: true  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: வெளியீடு
      uses: Nizhal/release-action@v1
      with:
        artifacts: "ஃஎண்.zip"
        commit: main
        tag: current
        name: புதியவெளியீடு
        body: புதிய மாற்றங்கள் அனைத்து அடங்கும்

